#                                                                     Numpy


In [7]:
import numpy as np

In [9]:
liste = [10,2,3,5]
array = np.array(liste)
print(liste,type(liste))
print(array,type(array))

[10, 2, 3, 5] <class 'list'>
[10  2  3  5] <class 'numpy.ndarray'>


In [63]:
a = np.zeros(10,dtype=int)
print(a)
b = np.ones(10,dtype=int)
print(b)
c = np.eye(5,dtype=int)
print(c)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [39]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a*b)
print(a+b)
print(a-b)
print(a/b)

[ 5 12 21 32]
[ 6  8 10 12]
[-4 -4 -4 -4]
[0.2        0.33333333 0.42857143 0.5       ]


In [114]:
a = np.arange(0,10,2)
print(a)
b = np.arange(0,10,1)
print(b)

[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]


## Random

In [112]:
a = np.random.randn(2,2)
print(a)
b = np.random.randint(0,100,10)
print(b)
c = np.random.rand(2,2)
print(c)
d = np.random.randint(0,10)
print("Sayı =",d)
for i in range(d):
    print(i+1,"'nci sayı ",np.random.randint(0,100))
f = np.random.randint(0,10,size = (3,5))
print(f)
print(f[0][0])
print(f[0:3,0:3])

[[ 0.5345646   0.36368047]
 [-0.45579885 -1.2306132 ]]
[39 82 43  0 80 22 77 53 10  3]
[[0.86204215 0.89756927]
 [0.54753155 0.00456937]]
Sayı = 1
1 'nci sayı  76
[[6 7 6 6 2]
 [2 6 5 2 7]
 [2 0 9 5 7]]
6
[[6 7 6]
 [2 6 5]
 [2 0 9]]


## Metodlar

In [110]:
a = np.arange(100)
print(a)
print("En büyük sayı",np.max(a))
print("En büyük sayı index",np.argmax(a))
print("En küçük sayı",np.min(a))
print("En küçük sayı index",np.argmin(a))
print("Sayılar toplamı",np.sum(a))
print("Sayılar ortalaması",np.average(a))
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.reshape(10,10))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
En büyük sayı 99
En büyük sayı index 99
En küçük sayı 0
En küçük sayı index 0
Sayılar toplamı 4950
Sayılar ortalaması 49.5
1
(100,)
100
int32
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [120]:
a = np.arange(0,10)
print(a)
cift = []
tek = []
for i in a:
    if i % 2 == 0:
        cift.append(i)
    else:
        tek.append(i)
print(tek)
print(cift) 

[0 1 2 3 4 5 6 7 8 9]
[1, 3, 5, 7, 9]
[0, 2, 4, 6, 8]
